"""Baseline migration

Revision ID: 863ba6541359
Revises: 
Create Date: 2026-09-27 00:23:34.259786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '863ba6541359'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venues_fts_config')
    op.drop_table('venues_fts_content')
    op.drop_table('feed_comments')
    op.drop_table('venues_fts_docsize')
    op.drop_table('venues_fts_data')
    op.drop_table('venues_fts')
    op.drop_table('venues_fts_idx')
    op.drop_table('feed_likes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_likes',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('target_type', sa.TEXT(), nullable=False),
    sa.Column('target_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type', 'target_id', 'user_id')
    )
    op.create_table('venues_fts_idx',
    sa.Column('segid', sa.NullType(), nullable=False),
    sa.Column('term', sa.NullType(), nullable=False),
    sa.Column('pgno', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term'),
    sqlite_with_rowid=False
    )
    op.create_table('venues_fts',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('address', sa.NullType(), nullable=True),
    sa.Column('city', sa.NullType(), nullable=True)
    )
    op.create_table('venues_fts_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('block', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venues_fts_docsize',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sz', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_comments',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.Column('author_name', sa.TEXT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.TEXT(), nullable=False),
    sa.Column('likes_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venues_fts_content',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('c0', sa.NullType(), nullable=True),
    sa.Column('c1', sa.NullType(), nullable=True),
    sa.Column('c2', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venues_fts_config',
    sa.Column('k', sa.NullType(), nullable=False),
    sa.Column('v', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('k'),
    sqlite_with_rowid=False
    )
    # ### end Alembic commands ###
